### ISSUE TITLE
Question about use of global variable in the Simple Example

### ISSUE THREAD

**Issue by DonWT** [koendv/FloatToAscii#1]
In the Simple example you have:

`String s;  // global variable to avoid memory fragmentation`

Would a static String declaration inside the function calling FloatToAscii also avoid the memory fragmentation issue?

(I prefer to avoid global variables).

**Comment by koendv** [comment]
Hi. Thank you for your comment.

ftoa() is a small routine to accurately print single-precision floating point numbers. This is about a tangential issue: memory management on embedded systems.

If you have a device that is switched on but never switched off, avoiding memory fragmentation may be an issue. Memory fragmentation means available memory has holes, like a Swiss cheese. Instead of one nice, big contiguous chunk of free memory, you have many small non-contiguous chunks. Memory requests then fail, because no sufficiently large *contiguous* free memory block is available.

I'm going to give one example with a character array and one with a String, and look at what happens to memory. First with a character array:

```
function called_often()
{
    ...
    char s[16];
    float f;
    ...
    ftoa(s, sizeof(s), f, -1);
    ...
}
```

When function called_often is executed, 16 bytes are allocated on the stack for the character array s. When the function exits, these 16 bytes are become available again.

Now with String:
```
function called_often()
{
    ...
    String s;
    float f;
    ...
    FloatToAscii(s, f, -1);
    ...
}
```
When function called_often is executed,  string length and a pointer to a character array are allocated on the stack. The actual character array itself is realloc()'ed on the heap, and free()'d when the function exits and the String destructor is called. If you execute this in a loop, you have a flurry of memory allocated and freed, and the possibility of memory fragmentation.

Now contrast with this:
```
String s;
...
function called_often()
{
    ...

    float f;
    ...
    FloatToAscii(s, f, -1);
    ...
}
```
The difference is that the String is never destroyed, the character array is not free()'d, so no memory fragmentation occurs. After a few calls, the character array has grown to a sufficient size, and stays that large.

If you're writing a program for pc, all this is usually not a problem. But for an embedded system with little ram that is running 24/24, 7/7, this may be an issue.

What I usually do is check the amount of free memory. As an example, this is a screen of my soldering iron: ![about](https://raw.githubusercontent.com/koendv/t12-958/main/pictures/ksger_t12_v20.jpg) 

The routine that prints free memory is here:  [free_ram.h](https://github.com/koendv/t12-958/blob/main/Arduino/t12-958/free_ram.h) and  [free_ram.cpp](https://github.com/koendv/t12-958/blob/main/Arduino/t12-958/free_ram.cpp) .  Just let the system run for a day, and check that, after the first few minutes, available memory stays more or less the same.

Does this answer your question?

**Comment by koendv** [comment]
*static* would work, too:

```
function called_often()
{
    ...
    static String s;
    float f;
    ...
    FloatToAscii(s, f, -1);
    ...
}
```

**Comment by DonWT** [comment]
Thank you for your quick response and for the details given.

You ask: "Does this answer your question?"

I would say not really but you have given me the tools to answer it myself!

My question was: Why not use a *static* String variable rather than a
*global* String variable?  I believe that  static variables are also fixed
in space - although I am not too sure about static Strings.  An ancillary
question might be why not declare the static String variable inside your
function?

My application is for a battery driven midi controller that would run
disconnected for long periods. I want to use your function as part of my
battery monitoring code where I maintain a display of the current battery
level, so it would be called fairly frequently.

Thx.  Don.

**Comment by koendv** [comment]
Using a 'static' String inside a function will work, too.
